apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-gw
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-gw
  template:
    metadata:
      labels:
        app: app-gw
    spec:
      containers:
      - name: app-gw
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-gw
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: ClusterIP
  selector:
    app: app-gw
  ports:
  - port: 80
    targetPort: 80
